FROM rabbitmq:3.12-management

RUN apt-get update && apt-get install -y curl

ENV PLUGIN_VERSION=3.12.0

RUN curl -L -o /plugins/rabbitmq_delayed_message_exchange-${PLUGIN_VERSION}.ez \
    https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v${PLUGIN_VERSION}/rabbitmq_delayed_message_exchange-${PLUGIN_VERSION}.ez

RUN rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange

RUN apt-get remove -y curl && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*
